variables:
  environment: "Develop"
  GIT_SSL_NO_VERIFY: "true"


stages:
  - build
  - deploy
  - scan code


build:
  stage: build
  tags:
     - Paul Test

  script:
    - yarn install
    - yarn global add gatsby-cli
    - cd ./packages/apps/storybook
    - yarn build
    - cd ../www
    - yarn build
    - aws s3 sync ./public s3://puredauk-gats-s3-dev-01 --delete --acl "public-read"

scan code:
    type: build
    tags:
        - gitlab-aws
    image:
        name: newtmitch/sonar-scanner
        entrypoint: ['']
    cache:
        paths:
            - /root/.sonar/cache
    variables:
        SONAR_URL: https://sonar.eon-cds.de
#allow_failure: true
    script:
        - sonar-scanner
          -Dsonar.host.url=$SONAR_URL
          -Dsonar.projectKey=$CI_PROJECT_NAME
          -Dsonar.projectName=$CI_PROJECT_NAME
          -Dsonar.projectVersion=$CI_PIPELINE_ID
          -Dsonar.projectBaseDir=.
          -Dsonar.sources=./
          -Dsonar.login=$SONAR_TOKEN
