stages:
  - lint and test
  - build
  - security scan
  - deploy DEV
  - test DEV
  - deploy FE-INT
  - test FE-INT
  - deploy PRP
  - test PRP
  - deploy PRD
  - test PRD

a11y test:
  stage: lint and test
  tags:
    - DEV
  image:
    name: node:latest
  script:
    - yarn install
    - yarn test:a11y
  only:
    - merge_requests

lint:
  stage: lint and test
  tags:
    - DEV
  image:
    name: node:latest
  script:
    - yarn install
    - yarn lint
  only:
    - merge_requests

unit test:
  stage: lint and test
  tags:
    - DEV
  image:
    name: node:latest
  script:
    - yarn install
    - yarn test
  only:
    - merge_requests

build DEV:
  stage: build
  tags:
    - DEV
  script:
    - yarn install
    - yarn global add gatsby-cli
    - cd ./packages/apps/storybook
    - yarn build
    - cd ../www
    - printenv > ./.env.staging
    - cat ./.env.staging
    - yarn build:staging
  artifacts:
    paths:
      - ./packages/apps/storybook/build
      - ./packages/apps/www/public
      - ./packages/apps/api
  environment:
    name: DEV
  only:
    - merge_requests
    - develop

build FE-INT:
  stage: build
  tags:
    - FE-INT
  script:
    - yarn install
    - yarn global add gatsby-cli
    - cd ./packages/apps/www
    - printenv > ./.env.production
    - cat ./.env.production
    - yarn build:staging
  artifacts:
    paths:
      - ./packages/apps/www/public
  environment:
    name: FE-INT
  only:
    - master

build PRP:
  stage: build
  tags:
    - PRP
  script:
    - yarn install
    - yarn global add gatsby-cli
    - cd ./packages/apps/www
    - printenv > ./.env.production
    - cat ./.env.production
    - yarn build:production
  artifacts:
    paths:
      - ./packages/apps/www/public
  environment:
    name: PRP
  only:
    - master

build PRD:
  stage: build
  tags:
    - PRD
  script:
    - yarn install
    - yarn global add gatsby-cli
    - cd ./packages/apps/www
    - printenv > ./.env.production
    - cat ./.env.production
    - yarn build:production
  artifacts:
    paths:
      - ./packages/apps/www/public
  environment:
    name: PRD
  only:
    - master

SONAR:
  stage: security scan
  tags:
    - gitlab-aws
  image:
    name: newtmitch/sonar-scanner
    entrypoint: ['']
  cache:
    paths:
      - /root/.sonar/cache
  variables:
    SONAR_URL: https://sonar.eon-cds.de
  script:
    - sonar-scanner
      -Dsonar.host.url=$SONAR_URL
      -Dsonar.projectKey=$CI_PROJECT_NAME
      -Dsonar.projectName=$CI_PROJECT_NAME
      -Dsonar.projectVersion=$CI_PIPELINE_ID
      -Dsonar.projectBaseDir=.
      -Dsonar.sources=./
      -Dsonar.login=$SONAR_TOKEN
  only:
    - merge_requests
    - develop

deploy Gatsby DEV:
  stage: deploy DEV
  tags:
    - DEV
  script:
    - aws s3 sync ./packages/apps/www/public s3://puredauk-gats-s3-dev-01 --delete --acl "public-read"
  dependencies:
    - build DEV
  environment:
    name: DEV
  only:
    - develop
    
deploy Gatsby DEV:
  stage: deploy DEV
  tags:
    - DEV
  script:
    - aws s3 sync ./packages/apps/api s3://puredauk-poc-s3-dev-01 --delete --acl "public-read"
  dependencies:
    - build DEV
  environment:
    name: DEV
  only:
    - develop    
    


deploy Storybook DEV:
  stage: deploy DEV
  tags:
    - DEV
  script:
    - aws s3 sync ./packages/apps/storybook/build s3://puredauk-gats-s3-dev-02/build --delete --acl "public-read"
  dependencies:
    - build DEV
  environment:
    name: DEV
  only:
    - develop

unit test DEV:
  stage: test DEV
  tags:
    - DEV
  image:
    name: node:latest
  script:
    - yarn install
    - yarn test
  only:
    - develop

e2e test Gatsby DEV:
  stage: test DEV
  tags:
    - DEV
  script:
    - yarn test:e2e
  environment:
    name: DEV
  only:
    - develop

deploy Gatsby FE-INT:
  stage: deploy FE-INT
  tags:
    - FE-INT
  script:
    - aws s3 sync ./packages/apps/www/public s3://puredauk-gats-s3-fe-int-01 --delete --acl "public-read"
  dependencies:
    - build FE-INT
  environment:
    name: FE-INT
  only:
    - master

smoke test Gatsby FE-INT:
  stage: test FE-INT
  tags:
    - FE-INT
  script:
    - yarn test:e2e:smoke
  environment:
    name: FE-INT
  only:
    - master

deploy Gatsby PRP:
  stage: deploy PRP
  tags:
    - PRP
  script:
    - aws s3 sync ./packages/apps/www/public s3://puredauk-gats-s3-prp-01 --delete
  dependencies:
    - build PRP
  environment:
    name: PRP
  only:
    - master
  when: manual
  allow_failure: false

smoke test Gatsby PRP:
  stage: test PRP
  tags:
    - PRP
  script:
    - yarn test:e2e:smoke
  environment:
    name: PRP
  only:
    - master

deploy Gatsby PRD:
  stage: deploy PRD
  tags:
    - PRD
  script:
    - aws s3 sync ./packages/apps/www/public s3://puredauk-gats-s3-prd-01 --delete
  dependencies:
    - build PRD
  environment:
    name: PRD
  only:
    - master
  when: manual
  allow_failure: false

smoke test Gatsby PRD:
  stage: test PRD
  tags:
    - PRD
  script:
    - yarn test:e2e:smoke
  environment:
    name: PRD
  only:
    - master
