version: 0.2

env:
  variables:
    PR: "x"
    environment: "Develop"
    S3Bucket: "s3://da-codepipeline-bucket"
    #branch: $(git branch | grep \* | cut -d ' ' -f2)
phases:
    install:
      runtime-versions:
        nodejs: 10
      commands:
            - 'touch .yarnignore'
            - 'echo $branch'
            - 'yarn global add gatsby-cli'
    pre_build:
        commands:
            - echo Running gatsby...
            #- gatsby new gatsby-site
            - echo Installing source yarn dependencies...
            - 'yarn install'
            #- 'gatsby develop'
    build:
        commands:
            - echo Build started on `date`
            - 'cd ./packages/apps/storybook'
            #- 'yarn build'
            #- 'gatsby build'

    post_build:
        commands:
            - 'aws s3 sync "./build" $S3Bucket --delete --acl "public-read"'
artifacts:
    base-directory: public
    files:
        - '**/*'
    discard-paths: yes
