version: 0.2
phases:
    install:
      runtime-versions:
        nodejs: 10
      commands:
            - 'touch .yarnignore'
            - 'yarn global add gatsby-cli'
    pre_build:
        commands:
            - echo Running gatsby...
            #- gatsby new gatsby-site
            - echo Installing source yarn dependencies...
            - 'yarn install'
            - 'gatsby develop'
    build:
        commands:
            - echo Build started on `date`
            - 'gatsby build'

    post_build:
        commands:
            - 'aws s3 sync "public/" "s3://da-gatsby-bucket" --delete --acl "public-read"'
artifacts:
    base-directory: public
    files:
        - '**/*'
    discard-paths: yes
