module.exports = {
  automock: false,
  collectCoverage: false,
  moduleFileExtensions: ['js', 'ts', 'tsx', 'graphql'],
  collectCoverageFrom: [
    'packages/components/**/*.{ts,tsx,js}',
    'packages/pages/**/*.{ts,tsx,js}',
    'packages/redux/**/*.{ts,tsx,js}',
    'packages/utils/**/*.{ts,tsx,js}',
    '!packages/components/user-switch/**/*.{ts,tsx,js}',
    '!packages/pages/form-example/**/*.{ts,tsx,js}',
    '!packages/pages/login/**/*.{ts,tsx,js}',
    '!packages/utils/test-support/**/*.{ts,tsx,js}',
    '!packages/utils/show-in-dev-only/**/*.{ts,tsx,js}',
    '!packages/{components,pages}/**/index.{ts,tsx,js}',
    '!packages/utils/{env,browser-support}/**',
    '!**/*.stories.{ts,tsx,js}',
    '!packages/**/*.mock.{js,ts,tsx}',
    '!**/node_modules/**',
    '!**/vendor/**',
    '!**/form-example/**',
  ],
  coverageReporters: ['text', 'cobertura', 'lcov'],
  coveragePathIgnorePatterns: ['/node_modules/', '/packages/components/icons/'],
  coverageDirectory: './build/reports/coverage',
  moduleNameMapper: {
    '^\\@somo/pda-(components|apps)-([a-z|-]*)$': '<rootDir>/packages/$1/$2/src/index.ts',
    '.+\\.(jpg|jpeg|png|gif|webp|webm)$': 'identity-obj-proxy',
    '.+\\.(css|pcss)$': '<rootDir>/__scripts__/identity-obj-proxy-esm.js',
    'dialog-polyfill': '<rootDir>/__mocks__/dialog-polyfill.ts',
    '.+\\.(svg)$': '<rootDir>/__mocks__/svg.ts',
    '^lodash-es$': '<rootDir>/node_modules/lodash/index.js',
  },
  preset: 'ts-jest',
  reporters: ['default', 'jest-junit'],
  roots: ['<rootDir>'],
  setupFilesAfterEnv: ['<rootDir>/__scripts__/setup-tests.ts', 'jest-localstorage-mock'],
  testEnvironment: 'enzyme',
  testURL: 'http://localhost',
  testPathIgnorePatterns: [
    '/node_modules/',
    '<rootDir>/packages/apps/e2e',
    '<rootDir>/packages/apps/www/.cache',
    '<rootDir>/packages/apps/www/public',
  ],
  transform: {
    '\\.(gql|graphql)$': 'jest-transform-graphql',
  },
  globals: {
    __PATH_PREFIX__: '',
    ___loader: '',
  },
};
