export const GET_TOKEN_REQUEST = '@SOCKET/GET_TOKEN_REQUEST';
export const GET_TOKEN_SUCCESS = '@SOCKET/GET_TOKEN_SUCCESS';
export const GET_TOKEN_FAILURE = '@SOCKET/GET_TOKEN_FAILURE';

export const SET_USER_ID = '@SOCKET/SET_USER_ID';
