# Develop build spec to create build artifacts, sync to develop test environment
# Typically runs automatically on commit to develop branch
version: 0.2
env:
  variables:
    environment: "Develop"
    S3Bucket: "s3://da-codepipeline-bucket"
phases:
    install:
      runtime-versions:
        nodejs: 10
      commands:
            - 'touch .yarnignore'
            - 'yarn global add gatsby-cli'
    pre_build:
        commands:
            - echo Installing source yarn dependencies...
            - 'yarn install'
    build:
        commands:
            - echo Build started on `date`
            - 'cd ./packages/apps/storybook'
            - 'yarn build'
    post_build:
        commands:
            - 'aws s3 sync "./build" $S3Bucket/$CODEBUILD_SOURCE_VERSION/ --delete --acl "public-read"'
artifacts:
    files:
        - '**/*'
