export const INIT_FORM = '@SOCKET/INIT_FORM';
export const CLEAR_FORM = '@SOCKET/CLEAR_FORM';
export const UPDATE_FORM = '@SOCKET/UPDATE_FORM';
export const SET_ERRORS = '@SOCKET/SET_ERRORS';
export const SET_FORM_ERRORS = '@SOCKET/SET_FORM_ERRORS';
export const CLEAR_FORM_ERRORS = '@SOCKET/CLEAR_FORM_ERRORS';
