name: Gatsby build

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: Borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: install and build Gatsby
      - uses: './packages/apps/www'
        run: |
          yarn global add gatsby-cli
          echo Build started on `date`
          yarn build
        env:
          CI: true
