on:
  pull_request:
    branches:
      - develop

jobs:
  Linting:
    name: Linting CSS & TypeScript
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Yarn install
        run: yarn

      - name: Linting CSS
        run: yarn lint:css

      - name: Linting TypeScript
        run: yarn lint:ts

        env:
          CI: true
