name: Unit Tests

on:
  pull_request:
    branches:
      - develop

jobs:
  Testing:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Yarn install
        run: yarn

      - name: Run Tests
        run: yarn test

        env:
          CI: true
